name: measurements
description: A new flutter plugin project.
version: 0.0.1
author: arconsis IT-Solutions GmbH
homepage: "https://github.com/ChristianNavolskyi/measurements"

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: 1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.arconsis.measurements
    pluginClass: MeasurementsPlugin
  assets:
    - assets/images/example_portrait.png
    - assets/images/example_landscape.png